# Generated by Django 6.0.7 on 2026-07-29 01:19

import apps.security.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('FILE', 'File'), ('URL', 'URL')], max_length=10)),
                ('target', models.CharField(help_text='Original filename or scanned URL.', max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.security.models.scan_upload_path)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLEAN', 'Clean'), ('SUSPICIOUS', 'Suspicious'), ('MALICIOUS', 'Malicious'), ('ERROR', 'Error')], default='PENDING', max_length=12)),
                ('security_score', models.PositiveSmallIntegerField(blank=True, help_text='0-100, higher is safer.', null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_scan_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('scan_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='security.scanlog')),
            ],
            options={
                'db_table': 'security_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(max_length=500, unique=True)),
                ('indicator_type', models.CharField(choices=[('FILE_HASH', 'File Hash (SHA-256)'), ('DOMAIN', 'Domain'), ('URL', 'URL'), ('IP', 'IP Address')], max_length=10)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threat_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Threat intel entries',
                'db_table': 'security_threat_intel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['user', '-created_at'], name='security_sc_user_id_3319e3_idx'),
        ),
        migrations.AddIndex(
            model_name='scanlog',
            index=models.Index(fields=['status'], name='security_sc_status_bc59af_idx'),
        ),
    ]
